# Generated by Django 3.1 on 2020-08-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
